[bumpver]
current_version="1.5.1"
version_pattern="MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message="bump version {old_version} -> {new_version}"
commit=true
tag=true
push=false

[bumpver.file_patterns]
"README.md"=["version={version}"]
"bumpver.toml"=['current_version="{version}"']
"pyproject.toml"=['version="{version}"']
"cxxbuild/cxxbuild.py"=["cxxbuild={version}"]
"setup.py"=["version='{version}'"]
"docs/source/conf.py"=["{version}"]
