[all]
fmt_cmake={ alias="fmt", git="https://github.com/fmtlib/fmt.git", tag="9.1.0", links=[
    "fmt"
], build="cmake" }
fmt_bazel={ alias="fmt", bcr="fmt", version="9.1.0", links=["fmt"], build="bazel" }
pthread={ triplet="!windows" }

[test]
Catch2={ git="https://github.com/catchorg/Catch2.git", tag="v3.5.1", links=[
    "Catch2::Catch2WithMain"
], build="cmake" }
catch2={ git="https://github.com/catchorg/Catch2.git", links=[
    "catch2_main"
], commit="f981c9cbcac07a2690e5a86767eba490b5465463", build="bazel" }

[dev]
bazel_win={ alias="bazel", choco=["bazelisk"], triplet="windows" }
bazel_linux={ alias="bazel", npm=["bazelisk"], triplet="linux" }
ninja=[{ choco=["ninja"], triplet="windows" }, { apt=["ninja-build"], triplet="linux" }]
cmake={ pip=["cmake"], deps=["ninja"] }
conan={ pip=["conan"] }
