name: Demo on windows, linux and macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
      

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install ninja-build, bazelisk and local dependencies (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install ninja-build -y
        python3 -m pip install -r requirements.txt
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        bash -i -c "nvm install --lts"
        bash -i -c "sudo npm install -g @bazel/bazelisk"
        bash -i -c "sudo apt install clang-19 clang-tools-19 libc++-19-dev"
    - name: Install ninja-build, bazel and local dependencies (macos)
      if: contains(matrix.os, 'macos')
      run: |
        brew install ninja
        brew install bazelisk
        python3 -m pip install -r requirements.txt --break-system-packages
    - name: Install bazel and local dependencies (windows)
      if: contains(matrix.os, 'windows')
      run: |
        choco install bazel
        python3 -m pip install -r requirements.txt
    - name: Install cmake with pipx (All)
      run: |
        pipx install cmake
    - name: demo-project1 (cmake)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project1
    - name: demo-project1 (bazel ubuntu)
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project1 --bazel
    - name: demo-project1 (bazel macos)
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project1 --bazel
    - name: demo-project2 (cmake)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2
    - name: demo-project2 (bazel ubuntu)
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2 --bazel
    - name: demo-project2 (bazel macos)
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2 --bazel
    - name: demo-project2 (windows cmd)
      if: contains(matrix.os, 'windows')
      shell: cmd
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2
    - name: demo-project3 (cmake)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project3
    - name: demo-project3 (bazel ubuntu)
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project3 --bazel
    - name: demo-project3 (bazel macos)
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project3 --bazel
    - name: demo-project4 C++20 (cmake)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project4 --c++20
    - name: demo-project4 C++20 (cmake)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project4 --c++20 --bazel
    - name: demo-project5 (cmake only)
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project5
    - name: demo-project6 (cmake only) - ubuntu
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        cd demo/project6/ && ./get_optframe.sh
        cd ../../ && python3 cxxbuild/cxxbuild.py demo/project6
    - name: demo-project6 (cmake only) - macos
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        cd demo/project6/ && ./get_optframe.sh
        cd ../../ && python3 cxxbuild/cxxbuild.py demo/project6
    - name: demo-project6 (cmake only) - windows
      if: contains(matrix.os, 'windows')
      shell: bash
      run: |
        cp demo/project6/cxxdeps.windows.txt demo/project6/cxxdeps.txt
        python3 cxxbuild/cxxbuild.py demo/project6
    - name: demo-project7 C++23 (cmake) - Windows ok MSVC 19.43, ubuntu broken on gcc 13 
      if: contains(matrix.os, 'windows')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project7 --c++23
    - name: demo-project7 C++23 (cmake) - MacOS ok Clang 15, ubuntu broken on gcc 13 
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project7 --c++23
    - name: demo-project7 C++23 (cmake) - Ubuntu trying gcc 14
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project7 --c++23 --compiler "/usr/bin/g++-14"
    - name: demo-project8 C++23 (cmake) - Windows
      if: contains(matrix.os, 'windows')
      shell: bash
      run: |
        cl /std:c++latest /EHsc /nologo /W4 /c "%VCToolsInstallDir%\modules\std.ixx"
        python3 cxxbuild/cxxbuild.py demo/project8 --c++23 --import std --cmake-unset BOOST_UT_DISABLE_MODULE
    - name: demo-project8 C++23 (cmake) - MacOS
      if: contains(matrix.os, 'macos')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project8 --c++23 --import std --cmake-unset BOOST_UT_DISABLE_MODULE
    - name: demo-project8 C++23 (cmake) - Ubuntu
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project8 --c++23 --compiler "/usr/bin/clang++-19" --stdlib libc++ --import std --cmake-unset BOOST_UT_DISABLE_MODULE




