name: Demo on windows, linux and macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
      

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install ninja-build (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install ninja-build -y
    - name: Install ninja-build and dependencies (macos)
      if: contains(matrix.os, 'macos')
      run: |
        brew install ninja
        python3 -m pip install -r requirements.txt --break-system-packages
    - name: Install cmake with pip
      run: |
        pipx install cmake
    - name: Install local cxxbuild.py dependencies (Ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        python3 -m pip install -r requirements.txt
    - name: Install local cxxbuild.py dependencies (Windows)
      if: contains(matrix.os, 'windows')
      run: |
        python3 -m pip install -r requirements.txt
    - name: demo-project1
      shell: bash
      run: |
        ls -la
        pwd
        python3 cxxbuild/cxxbuild.py demo/project1
    - name: demo-project2
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2
    - name: demo-project2 (windows cmd)
      if: contains(matrix.os, 'windows')
      shell: cmd
      run: |
        python3 cxxbuild/cxxbuild.py demo/project2
    - name: demo-project3
      shell: bash
      run: |
        python3 cxxbuild/cxxbuild.py demo/project3



